name: Manual Build and Publish Artifact

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and Publish Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Project
        run: ./gradlew build

      - name: Publish Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/libs/